idserver.url=http://52.62.218.138:8080
idserver.ws.url=ws://52.62.218.138:8080/ws
p2p.port.range.start=50000
p2p.port.range.end=60000
screen.capture.maxWidth=1280
screen.capture.maxHeight=720
screen.capture.quality=0.35
screen.capture.fps=8
heartbeat.interval.seconds=30
